version: '3'
services:
  web:
    build: .
    labels:
      com.example.description: "szweb"
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    sysctls:
      net.core.somaxconn: '511'
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
